### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by lobcare** [davist1025/Bloomwood#1]
Hi, Tyler.
I am Yuichi from Singapore.
I have got an idea and I need a friend for that.
I was looking for someone who can collaborate with me and find you.
And I am sure you are the right person for me.

I hope we can discuss more. 
Here is my skype address and please contact me when you are free.
live:.cid.cf6419bd5f2807be

Sincerely.
Yuichi.

**Comment by davist1025** [comment]
Hi, @lobcare!

I'm not looking for any collaborators at this time, but thank you for the interest!

**Comment by lobcare** [comment]
Thanks for your reply.
Can we talk this over ?
I think it could be the big chance for us.
We could make a bundle for sure.
If possible, please contact me via skype.

I am waiting for your reply.
